typography_spectrum: 0.9023511470295489
color:
  saturation: 0.9014337
  brandStrength: 0.07706093
  lightness: 1
  brandColors:
    - '#0D0D0D'
    - '#FFFFFF'
    - '#665D4C'
    - '#D3CCB8'
    - '#8D9B9E'
  rhythmicContrast: 0.6362007
github: true
layout_spectrum: 0.6756272
name: Think-Like.me | Music
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Music
content: []
description: 'Enjoy the same music as I do.... '
url: 'https://music.think-like.me/'
author:
  name: Kristoffer Svarre
  email: ksvarre@gmail.com
  url: 'https://linkedin.com/in/ksvarre'
analytics:
  google: UA-79126334-1
